language: cpp
install: sudo Tools/Precise/install-deps
script: Tools/Precise/build
deploy:
  skip_cleanup: true
  provider: s3
  artifacts: true
  region: eu-west-1
  paths: Wide/Build/x64/Release
  upload-dir: builds/$TRAVIS_BUILD_NUMBER
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  bucket: $ARTIFACTS_BUCKET