language: cpp
install: sudo Tools/Precise/install-deps
script: Tools/Precise/build
deploy:
  skip_cleanup: true
  provider: s3
  artifacts: true
  s3_region: "eu-west-1"
  paths: Wide/Build/x64/Release
  upload-dir: builds/$TRAVIS_BUILD_NUMBER