language: cpp
install: sudo ./InstallDependencies.sh
script: 
    - ./Build.sh
    - ./RunTests.sh
compiler: clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    - llvm-toolchain-precise-3.6
    packages:
    - llvm-3.6-dev
    - libclang-3.6-dev
    - clang-3.6
