language: cpp
install: 
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - $CXX --version 
    - sudo ./InstallDependencies.sh
script: 
    - ./Build.sh
    - ./RunTests.sh
compiler: gcc
