language: cpp
install: sudo Tools/Precise/install-deps
script: Tools/Precise/build
before_deploy: Tools/Precise/package
deploy:
  - skip_cleanup: true
    provider: s3
    artifacts: true
    region: eu-west-1
    local_dir: Packages
    upload-dir: builds/$TRAVIS_BUILD_NUMBER
    access_key_id: $ARTIFACTS_KEY
    secret_access_key: $ARTIFACTS_SECRET
    bucket: $ARTIFACTS_BUCKET
    acl: public_read
  - skip_cleanup: true
    provider: s3
    artifacts: true
    region: eu-west-1
    local_dir: Packages
    upload-dir: builds/latest
    access_key_id: $ARTIFACTS_KEY
    secret_access_key: $ARTIFACTS_SECRET
    bucket: $ARTIFACTS_BUCKET
    acl: public_read
