#!/bin/bash
sudo dnf install -y zlib-devel libarchive-devel ncurses-devel gcc-c++ boost-devel

# llvm+clang
wget http://llvm.org/releases/3.6.2/cfe-3.6.2.src.tar.xz -O _clang.tar.xz
wget http://llvm.org/releases/3.6.2/llvm-3.6.2.src.tar.xz -O _llvm.tar.xz
tar -xJf _clang.tar.xz
tar -xJf _llvm.tar.xz
mv cfe* clang
mv llvm* llvm
mv clang llvm/tools/
mkdir llvm_inst
mkdir llvm/build
cd llvm/build
cmake -G "Unix Makefiles" \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_ENABLE_RTTI=ON \
    -DLLVM_ENABLE_ASSERTIONS=OFF \
    -DCMAKE_INSTALL_PREFIX=../../llvm_inst .. && \
    make -j `nproc` DISABLE_ASSERTIONS=1 && \
    make install
cd $OLDPWD
cp -r -p llvm_inst/include llvm
mkdir llvm/Release+Asserts
cp -r -p llvm_inst/lib llvm/Release+Asserts

# premake 4.4
wget 'http://downloads.sourceforge.net/project/premake/Premake/4.4/premake-4.4-beta5-src.zip?r=&ts=1457475191&use_mirror=kent' -O _premake44.zip
unzip _premake44.zip
mv premake* premake
cd premake/build/gmake.unix
make
cd $OLDPWD