#!/usr/bin/env sh

sudo apt-get update -qq
sudo apt-get install -y libboost1.58-dev
sudo apt-get install -y llvm-3.6-dev
sudo apt-get install -y libclang-3.6-dev
sudo apt-get install -y premake4 
sudo apt-get install -y libarchive-dev
sudo apt-get install -y zlib1g-dev
sudo apt-get install -y ncurses-dev
