#!/usr/bin/env sh

sudo apt-add-repository ppa:ubuntu-toolchain-r/test -y
sudo add-apt-repository ppa:codegear/release -y
wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
sudo apt-add-repository "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main"
sudo apt-get update -qq
sudo apt-get install -y llvm-3.6-dev
sudo apt-get install -y libclang-3.6-dev
sudo apt-get install -y clang-3.6
sudo apt-get install -y premake4 
sudo apt-get install -y libarchive-dev
sudo apt-get install -y zlib1g-dev
sudo apt-get install -y ncurses-dev
sudo apt-get install -y g++-4.9
sudo update-alternatives --quiet --install /usr/bin/g++ g++ /usr/bin/g++-4.9 10

wget http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.bz2
tar -axf boost_1_59_0.tar.bz2
rm boost_1_59_0.tar.bz2
cd boost_1_59_0
./bootstrap.sh --prefix=/usr/local
sudo ./b2 link=static threading=multi runtime-link=static --with-program_options -d0 install
