#!/usr/bin/env sh
if ! test -e "Tests" ; then
    mkdir Tests
    mkdir Tests/Runner
    mkdir Tests/WideLibrary
fi
cp "Wide/Build/x64/Release/SemanticTest" Tests/Runner
cp -r Wide/SemanticTest/. Tests/Runner
cp -r Wide/WideLibrary/. Tests/WideLibrary
cd Tests/Runner
./SemanticTest
OUT=$?
cd ../..
exit $OUT

