#!/usr/bin/env sh
if ! test -e "Tests" ; then
    mkdir Tests
    mkdir Tests/Runner
    mkdir Tests/WideLibrary
fi
cp "Wide/Build/x64/Release/IntegrationTests" Tests/Runner
cp -r Wide/IntegrationTests/. Tests/Runner
cp -r Wide/WideLibrary/. Tests/WideLibrary
cd Tests/Runner
./IntegrationTests
OUT=$?
cd ../..
exit $OUT

